=== Basim108/engx-maturity/data/schemas/rule.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "rule.schema.json",
  "title": "Rule",
  "description": "An engineering excellence rule or practice that some maturity levels might contain.",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "ruleId": {
      "$ref": "types.schema.json#/$defs/uuid"
    },
    "statement": {
      "type": "string",
      "description": "Brief summary of a rule in imperative form for guidelines"
    },
    "question": {
      "type": "string",
      "description": "Brief summary of a rule in interrogative form for questionnaires/assessments"
    },
    "description": {
      "type": "string",
      "description": "Detailed explanation of the rule and its context"
    },
    "tags": {
      "type": "array",
      "minItems": 0,
      "uniqueItems": true,
      "items": {
        "type": "string",
        "description": "for better further search. For example, 'security', 'metrics', etc"
      }
    },
    "articles": {
      "type": "array",
      "minItems": 0,
      "items": {
        "$ref": "types.schema.json#/$defs/resourceUrl"
      }
    },
    "metrics": {
      "type": "array",
      "minItems": 0,
      "uniqueItems": true,
      "items": {
        "$ref": "types.schema.json#/$defs/uniqueId"
      }
    }
  },
  "required": ["ruleId", "question"]
}

=== Basim108/engx-maturity/data/rules/agile.rules.json
[
  {
    "ruleId": "03f31a64-3c7a-4543-8085-e69373f991d7",
    "question": "Do you have Definition of Ready criteria to take user story in sprint?",
    "tags": [
      "role:ba"
    ],
    "statement": "Introduce 'Definition of Ready' criteria to take user story in sprint."
  },
  {
    "ruleId": "313c4446-7f4f-4d93-b2c3-7454b173c17a",
    "question": "Do you have Definition of Done for user stories and sprint?",
    "tags": [
      "role:pm",
      "role:po"
    ],
    "statement": "Introduce 'Definition of Done' for user stories and sprint."
  },
  {
    "ruleId": "ff0ba187-b653-4bbd-b09d-dfe41286e714",
    "question": "Does team track sprint burn-down chart?",
    "tags": [
      "role:pm",
      "role:ba",
      "role:dev",
      "role:devops",
      "role:qa"
    ],
    "statement": "Track sprint burn-down chart."
  },
  {
    "ruleId": "a0cb34ea-eabb-46df-aabd-5349c0bc8705",
    "question": "Does team deliver software to the customer at the end of every sprint?",
    "tags": [
      "role:pm",
      "role:ba",
      "role:dev",
      "role:devops",
      "role:qa"
    ],
    "statement": "Ensure software delivery to the customer at the end of every sprint."
  },
  {
    "ruleId": "76e00546-61c1-425b-b503-a54e4e0d8b22",
    "question": "Is your sprint/iteration duration less than or equal to 2 weeks?",
    "tags": [
      "role:pm",
      "sdlc"
    ],
    "statement": "Ensure sprint/iteration duration is less than or equal to 2 weeks."
  },
  {
    "ruleId": "d3384f33-afac-4ee1-ab3b-d3d9052b0c7e",
    "question": "Do you have backlog grooming/refinement sessions before the start of each sprint/iteration?",
    "tags": [
      "role:pm"
    ],
    "statement": "Introduce backlog grooming/refinement sessions before the start of each sprint/iteration."
  },
  {
    "ruleId": "a6e5f7ad-fc58-4668-90b8-91d862191977",
    "question": "Are user stories accepted by a customer or product owner before sprint starting a sprint/iteration?",
    "tags": [
      "role:pm",
      "role:po"
    ],
    "statement": "Ensure user stories are accepted by a customer or product owner before starting a sprint/iteration."
  }
]

=== Basim108/engx-maturity/data/rules/requirement.rules.json
[
  {
    "ruleId": "e18b074f-7c74-430d-a686-ef0c1b6aa8a3",
    "statement": "Introduce rigorous requirements reviews and sign-offs.",
    "question": "Do you have rigorous requirements reviews and sign-offs?",
    "tags": [
      "role:ba",
      "sdlc:requirements"
    ],
    "metrics": [
      "review-time",
      "review-lead-time",
      "review-efficiency",
      "review-feedback",
      "post-release-changes"
    ]
  },
  {
    "ruleId": "7ee7b527-7f7d-4710-ac96-6c304e445740",
    "question": "Do you have a clear traceability matrix?",
    "tags": [
      "role:all",
      "sdlc:all"
    ],
    "statement": "Introduce a clear traceability matrix."
  },
  {
    "ruleId": "cd9369e6-135e-481e-9652-e8f5b1ab954b",
    "question": "Do you maintain your traceability matrix?",
    "tags": [
      "role:all",
      "sdlc:all"
    ],
    "statement": "Ensure maintenance of your traceability matrix."
  },
  {
    "ruleId": "a1070923-ebf0-43c0-8658-c06a3a4dc268",
    "question": "Does your traceability matrix link requirements to design elements, code modules, test cases, and ultimately, the delivered product?",
    "description": "This helps ensure that everything built can be traced back to a specific requirement and that all requirements are addressed.",
    "tags": [
      "role:all",
      "sdlc:all"
    ],
    "statement": "Ensure your traceability matrix links requirements to design elements, code modules, test cases, and ultimately, the delivered product."
  },
  {
    "ruleId": "83c278c2-81c6-4610-9977-20edf55c366d",
    "question": "Do you control changes to requirements?",
    "tags": [
      "role:ba",
      "role:pm"
    ],
    "metrics": [
      "post-release-changes"
    ],
    "statement": "Introduce requirement change management to control its changes."
  },
  {
    "ruleId": "38b896f4-4f3c-4458-947a-d7851959574b",
    "question": "Do you have a formal process for managing changes to requirements?",
    "tags": [
      "role:ba",
      "role:pm"
    ],
    "metrics": [
      "post-release-changes"
    ],
    "statement": "Introduce a formal process for managing changes to requirements."
  }
]
